#!/bin/bash
java -server -Xms128m -Xmx128m -XX:PermSize=128m -XX:MaxPermSize=128m -Xmn128m -XX:+UseParallelGC -XX:ParallelGCThreads=4 -Xloggc:gc_netty-demo.log -XX:+PrintGCDetails -Dfile.encoding=utf8 -jar  netty-demo-1.0-SNAPSHOT.jar  "7777"
echo "start netty-demo-1.0-SNAPSHOT.jar  success!"
